config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  resources :submissions, only: [:show], shallow: true do
    resources :reviews, only: [:create]
  end

  resources :exercices, only: [:index, :show] do
    resources :submissions, only: [:new, :create, :edit, :update]
    resources :bookmarks, only: [:create, :destroy]
    member do
      post 'toggle_favorite', to: "exercices#toggle_favorite"
    end
  end

  resources :users, only: [:index, :show]
  get 'dashboards', to: "dashboards#show"

end

app/models/exercice.rb
class Exercice < ApplicationRecord
  has_many :tags
  has_many :submissions
  acts_as_favoritable

  def has_submission?(user)
    submissions.where(user: user).any?
  end

  def user_submission(user)
    submissions.where(user: user).first
  end

end

app/controllers/exercices_controller.rb
class ExercicesController < ApplicationController
  before_action :authenticate_user!, only: :toggle_favorite

  def toggle_favorite
    @exercice = Exercice.find_by(id: params[:id])
    current_user.favorited?(@exercice) ? current_user.unfavorite(@exercice) : current_user.favorite(@exercice)
  end

  def index
    if params[:query]
      @exercices = Exercice.includes(:tags).where(tags:{title:params[:query]})
    else
      @exercices = Exercice.all
    end
    if turbo_frame_request?
      render partial: "exercices/partials/exercices", locals:{ exercices: @exercices}
    else
      render :index
    end
  end

  def show
    @exercice = Exercice.find(params[:id])
  end

  private

  def exercice_params
    params.require(:exercice).permit(:title, :details, :exp)
  end

end

app/views/exercices/partials/_exercices.html.erb
<%= turbo_frame_tag "exercices" do %>
  <div class="row">
      <div>
        <% exercices.each do |exercice| %>
          <div class="card-product d-flex">
            <div class=" ms-4">
              <span style="display: flex">
              <% if exercice.has_submission?(current_user) %>
                <%= link_to edit_exercice_submission_path(exercice, exercice.user_submission(current_user)), data: {turbo: "false"} do %>
                  <h3><%= exercice.title %></h3>
                <% end %>
              <% else %>
                <%= link_to new_exercice_submission_path(exercice), data: {turbo: "false"} do %>
                  <h3><%= exercice.title %></h3>
                <% end %>
              <% end %>

              <%exercice.tags.each do |tag|%>
                <div class= "tag rounded-pill text-bg-warning mx-2">
                  <p><%= tag.title %></p>
                </div>
              <% end %>
              </span>
              <p>Instruction : <%= exercice.instructions.first(140)%> [...] </p>
              <p>Exp : <strong><%= exercice.exp%></strong> </p>
            </div>
            <div class="m-4">
              <% if user_signed_in? %>
                <%= link_to toggle_favorite_exercice_path(exercice), data: {turbo_method: :post} do %>
                  <%= turbo_frame_tag "like_#{dom_id(exercice)}" do %>
                    <%= render partial: 'exercices/partials/like_button', locals: { exercice: exercice } %>
                  <% end %>
                <% end %>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/exercices/partials/_like_button.html.erb
<div class="like-icon mx-2 <%= 'bookmarks' if current_user && current_user.favorited?(exercice) %>" data-id="<%= exercice.id %>">
  <i class="fa-solid fa-bookmark"></i>
</div>