config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  resources :submissions, only: [:show], shallow: true do
    resources :reviews, only: [:create]
  end

  resources :exercices, only: [:index, :show] do
    resources :submissions, only: [:new, :create, :edit, :update]
    resources :bookmarks, only: [:create, :destroy]
    member do
      post 'toggle_favorite', to: "exercices#toggle_favorite"
    end
  end

  resources :users, only: [:index, :show]
  get 'dashboards', to: "dashboards#show"

end

app/views/shared/_banner_user.html.erb
<% if @user.banner_picture.attached? %>
  <% background_url = cl_image_path @user.banner_picture.key %>
<% else %>
  <% background_url = asset_path "default_banner.jpg" %>
<% end %>

<div class="banner-user" style="background-image: linear-gradient(rgba(0,0,0,0.6),rgba(0,0,0,0.6),rgba(0,0,0,0.6),rgba(0,0,0,0.6)), url(<%= background_url %>);">
  <div class="container">
      <div class="user-info row">
        <div class="user-left-panel col-8">
        <% if @user.avatar.attached? %>
          <%= cl_image_tag @user.avatar.key, height: 80, width: 90, crop: :thumb %>
        <% else %>
          <%= image_tag (asset_path("default_picture.jpg")), height: 90, width: 90 %>
        <% end %>
        <h1><%= image_tag (asset_path("flags/#{@user.country.downcase}.png")), style: "width: 32px;" %> <%= @user.username %></h1>
        <!-- <span class="fi fi-gr"></span> FLAG ICONS? -->
        <p>Member since: <%= @user.created_at.strftime("%d %B %Y") %></p>
        <p>Total XP: <%= @user.exp %></p>

        <% if current_user == @user %>
          <%= link_to "Edit Profile", edit_user_registration_path, class: "btn button-yellow" %>
        <% end %>
        </div>
        <div class="user-right-panel col-4">
          <div>
          <h4>My Achievements</h4>
          </div>
          <div class="achievements">
          <% if @user.beginners_luck? %>
            <%= image_tag (asset_path("achievements/BeginnersLuck.png")), width: "40px", class:"achievement-dyn-image", title:"Beginner's Luck\nComplete exercise on first attempt" %>
          <% end %>
          <%= image_tag (asset_path("achievements/EarlyAdopter.png")), width: "40px", class:"achievement-dyn-image", title:"Early Adopter\nUse JS Dojo in the first week of launch" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_code_editor.html.erb
<% must_show_solution = false %>

<div class="row">
  <div class="col-md-4 ">
    <div class="card-code-editor">
      <h4>Instructions: </h4>
      <p><%= @exercice.instructions %></p>
      <p>Warning: your function must be nammed :          <br>"<%= /const\s+(\w+)\s+(?==)/.match(@exercice.function_name) %>"</p>
      <hr>
      <p>XP earned on completion: <strong><%= @exercice.exp %></strong></p>
    </div>

    <div class="card-code-editor">
      <h4>Hint: </h4>
      <p><%= @exercice.details %></p>
      <hr>
      <h4>Examples:</h4>
      <p><%= @exercice.examples.html_safe %></p>
      <% if must_show_solution == true %>
        <p style="color: black !important">solution: <%= @exercice.solution %></p>
      <% end %>
    </div>


  </div>

  <div class="col-md-8" data-controller="editor">
      <div class="editor-header-label row">
        <div class="col-8">
          <h2>Your solution</h2>
        </div>
        <div class="col-4 d-flex mt-2 mr-2">
          <h5>Total attempts: <%= @submission.attempts_count %></h5>
        </div>
      </div>
      <div id="ace-div">
        <code id="ace-editor" data-editor-target="editor"><% if !@submission.user_code %><%= @exercice.function_name %><% else %><%= @submission.user_code %><% end %></code>
      </div>
    <div id="sub-editor-div">
      <div id="editor-form">
        <%= simple_form_for [@exercice, @submission], html: { data: { editor_target: "form"} } do |f| %>
          <%#= f.input :user_code, input_html: {class: 'input-color', data: {editor_target: "input"}} %>

          <%= f.hidden_field :user_code, class: 'input-color', data: {editor_target: "input"}%>
          <%= f.button :submit, '> Run', class: 'btn btn-success m-3 ', data: { action: "click->editor#submitCode" } %>
          <%# <button type="button" data-action="click->editor#submitCode" class="btn btn-success m-3">coucou</button> %>
        <% end %>
      </div>
    <% if @rakes %>
      <div id="validations-counter">
        <p>Validations: <%= @exercice_validations %> / <%= @rakes.length %></p>
      </div>
    <% end %>
    </div>

    <div>
      <h2>Output</h2>
      <div>
        <p>
          <%= @output %>
        </p>
      </div>
    </div>

    <div>
      <h2>Errors</h2>
      <div>
        <p>
          <%= @current_error %>
        </p>
      </div>
    </div>

    <% if @rakes_insights %>
      <div style="border: 1px solid gray; padding: 10px; margin-top: 30px;">
        <h2>Insights</h2>

        <% @rakes_insights.each_with_index do |rake_insight, index| %>

          <div>
            <span style="font-weight: bold">  Test n°<%= index + 1 %></span>
            <br>
            <span style="text-decoration: underline;">To be evaluated:</span>
            <br/>
            <%= rake_insight[:to_be_evaluated] ? rake_insight[:to_be_evaluated] : " ***nothing*** " %></p>
            <span style="text-decoration: underline;">Executed:</span>
            <br/>
            <%= rake_insight[:executed] ? rake_insight[:executed] : " ***nothing*** " %></p>
            <span style="text-decoration: underline;">Unit test:</span>
            <br/>
            <%= rake_insight[:unit_test] ? rake_insight[:unit_test] : " ***nothing*** " %></p>
            <span>Validation:</span>
            <% if rake_insight[:round_validation].nil? %>
            <span style="font-weight: bold; font-style: italic; color: whitesmoke;">No validation yet</span>
            <% elsif rake_insight[:round_validation] == true %>
            <span style="font-weight: bold; font-style: italic; color: green;">Correct!</span>
            <% elsif rake_insight[:round_validation] == false %>
            <span style="font-weight: bold; font-style: italic; color: red;">Incorrect!</span>
            <% else %>
            <span style="font-weight: bold; font-style: italic; color: pink;">Validation unknown</span>
            <% end %>
          </div>

          <% if index != @rakes_insights.length - 1%>
          <hr>
          <% end %>

        <% end %>

      </div>
  <% end %>

  <br>

</div>

<script src="https://releases.jquery.com/git/jquery-git.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/ace/1.15.3/ace.js"></script>
<script>
    //cdnjs.cloudflare.com/ajax/libs/ace/1.1.3/ace.js
    var theme = "ace/theme/twilight";
    var mode = "ace/mode/javascript";
    var editor = ace.edit("ace-editor");
    editor.setOptions({
      fontFamily: "courier",
      fontSize: "16pt"
    });
    editor.setTheme(theme);
    editor.getSession().setMode(mode);
    // editor.renderer.setShowGutter(false);
    $("#ace-mode").on("change", function () {
    editor.getSession().setMode("ace/mode/" + $(this).val().toLowerCase());
    });
    $("#ace-theme").on("change", function () {
    editor.setTheme("ace/theme/" + $(this).val().toLowerCase());
    });

</script>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_modal.erb
<div class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <p>attempts: <%= @submission.attempts_count%></p>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "/", class: "navbar-brand" do %>
      <%= image_tag asset_path("jsdojo/logo-full.png") %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Exercises", exercices_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Dashboard", dashboards_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Leaderboards", users_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown" style="padding-left: 3rem !important;">
            <% if current_user.avatar.attached? %>
              <%= cl_image_tag current_user.avatar.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% else %>
              <%= image_tag (asset_path("default_picture.jpg")), class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% end %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "My profile", user_path(current_user), class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>