config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  resources :submissions, only: [:show], shallow: true do
    resources :reviews, only: [:create]
  end

  resources :exercices, only: [:index, :show] do
    resources :submissions, only: [:new, :create, :edit, :update]
    resources :bookmarks, only: [:create, :destroy]
    member do
      post 'toggle_favorite', to: "exercices#toggle_favorite"
    end
  end

  resources :users, only: [:index, :show]
  get 'dashboards', to: "dashboards#show"

end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def show
    @unfinished_submissions = Submission.where(user: current_user, validation: false)
    @last_unfinished_submission = @unfinished_submissions&.last
    @total_wins = User.find(current_user.id).submissions.where(validation: true).count
    @never_tried = Exercice.excluding(current_user.exercices)
    @current_user_rank = current_user.rank
    @users_count = User.count
  end
end

app/views/dashboards/show.html.erb
<br>
<div class="parent">
  <div class="lastplayed">
        <h2>Resume last exercise</h2>
      <div class="d-flex py-3 flex-column">
        <% if @last_unfinished_submission %>
          <%= link_to @last_unfinished_submission.exercice.title, edit_exercice_submission_path(@last_unfinished_submission.exercice, @last_unfinished_submission) %>
          <p><%= @last_unfinished_submission.exercice.instructions %></p>
        <% end %>
      </div>
  </div>
  <div class="currentxp">
    <div class="mb-5">
      <h2>Total Wins</h2>
      <p><%= @total_wins %> games won</p>
    </div>
    <div class="mb-5">
      <h2>Ranking</h2>
      <p><%= ordinal_indicator(@current_user_rank) %> out of <%= @users_count %> players !</p>
    </div>
    <div class="mb-5">
      <h2>Total XP</h2>
      <p><%= current_user.exp %></p>
    </div>

  </div>
  <div class="streams">
    <h2>Featured Streams</h2>
    <iframe src="https://player.twitch.tv/?channel=elysiagriffin&parent=<%=request.host%>&autoplay=false" frameborder="0" allowfullscreen="true" scrolling="no" height="189" width="310"></iframe>
  </div>
  <div class="random">
    <h2>Start a Random Exercise</h2>
    <%= link_to "Random Exercise", exercice_path(@never_tried.sample), class: 'btn button-yellow ' %>
  </div>
  <div class="challenges">
    <h2>Achievements</h2>
    <%= image_tag (asset_path("achievements/ActiveUser.png")), class: "badge-opacity achievement-dyn-image", title: "Active User\nLogin 7 days in a row", width: "40px" %>
    <% if current_user.beginners_luck? %>
        <%= image_tag (asset_path("achievements/BeginnersLuck.png")), class: "achievement-dyn-image", title: "Beginner's Luck\nComplete exercise on first attempt", width: "40px"%>
    <% else %>
        <%= image_tag (asset_path("achievements/BeginnersLuck.png")), class: "badge-opacity achievement-dyn-image", title: "Beginner's Luck\nComplete exercise on first attempt", width: "40px"%>
    <% end %>
    <%= image_tag (asset_path("achievements/Bookmarker.png")), class: "badge-opacity achievement-dyn-image", title: "Bookmarker\nAdd an exercise as favorite", width: "40px" %>
    <%= image_tag (asset_path("achievements/Champ.png")), class: "badge-opacity achievement-dyn-image", title: "Champ\nFinish 10 exercises", width: "40px" %>
    <%= image_tag (asset_path("achievements/EarlyAdopter.png")), width: "40px", class: "achievement-dyn-image", title: "Early Adopter\nUse JS Dojo in the first week of launch" %>
    <%= image_tag (asset_path("achievements/Grandmaster.png")), class: "badge-opacity achievement-dyn-image", title: "Grandmaster\nFinish all exercises", width: "40px" %>
    <%= image_tag (asset_path("achievements/NoLife.png")), class: "badge-opacity achievement-dyn-image", title: "No-Life\nLogin 8 days in a row", width: "40px" %>
    <%= image_tag (asset_path("achievements/Ready2Code.png")), class: "badge-opacity achievement-dyn-image", title: "Ready2Code\nComplete your profile", width: "40px" %>
  </div>
</div>